apiVersion: v1	
kind: Service	
metadata:	
  name: backend	
spec:	
  ports:	
  - port: 8080	
    targetPort: 8080	
  selector:	
    app: backend
  type: ClusterIP  
  
  ---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend
  namespace: edu31
spec:
  host: backend-edu31.apps.211-34-231-82.nip.io
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: backend
    weight: 100    
  wildcardPolicy: None   

