apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: ghcr.io/shclub/edu12-3:master
        env:
        - name: REACT_APP_API_URL
          value: "http://backend:8080" 
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP   

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: front
  namespace: edu31
spec:
  host: front-edu31.apps.211-34-231-82.nip.io
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: front
    weight: 100    
  wildcardPolicy: None   
